### ISSUE TITLE
How beginner Friendly is this tutorial

### ISSUE THREAD

**Issue by ryaninja** [dwyl/flutter-todo-list-tutorial#11]
Hi, I'm new to flutter and the todo app tutorial seemed perfect for me to type in to practice my learning. It's this [tutorial](https://github.com/dwyl/flutter-todo-list-tutorial). I'm stuck very close to the start, at point 7- Create a "CustomButton"- it doesn't say where to put this code in.  

After doing a bit more investigation, experimentation and checking I wasn't asking a stupid question caused by me copying the code incorrectly when typing it out, and even experimenting with trying different places that would accept a new child class and I've noticed that in every code example containing a widget, the code isn't complete - there are no closing square brackets in any of the code examples in most of the guide as far as I can tell.  

It's strange because the instructions feel really comprehensive telling you exactly what to do, but despite being quite specific, it doesn't contain all the information you need to actually follow it?

Is the guide still incomplete and being worked on, or am I really being stupid, or is it just aimed at already accomplished developers?  Thanks a lot!

**Comment by nelsonic** [comment]
@ryaninja thanks for opening this issue to share your feedback.
At present this tutorial is not as beginner friendly as we would like it to be.
We recommend you follow the official guide: https://flutter.dev/docs/reference/tutorials

**Comment by ryaninja** [comment]
@nelsonic  - Hi thanks for getting back to me.  I'm not terribly adept at scripting, but I do have a good 15 years of windows server and database experience, so I'm not a complete newbie.  What I'm getting at is as this guide progresses if you want any constructive feedback from someone who isn't an experienced coder, but knows what to look for in a technical document or tutorial, please let me know and I'd be happy to help out however I can.  Thanks for what you have put up though, I will definitely come back to it when I have a bit more experience. :)
