### ISSUE TITLE
Is MOOR part of the Dwyl stack?

### ISSUE THREAD

**Issue by t0mhaines** [dwyl/flutter-todo-list-tutorial#15]
From what I can see, MOOR is just a wrapper around a SQLite database. Is there any reason Moor was used in the original tutorial over SQLite?

For a TodoList tutorial this may add unnecessary complexity (turning it into a Moor tutorial *not* a Todo one)

Is Moor planned to be used on other projects as well as a component of the Dwyl stack?

**Comment by nelsonic** [comment]
@th0mas while **`MOOR`** https://pub.dev/packages/moor_flutter has several useful features, 
it should not have been used in the original tutorial as it's complete overkill for a simple todo list.
A simple SQLite DB https://flutter.dev/docs/cookbook/persistence/sqlite is more than enough.

**Comment by nelsonic** [comment]
To answer your second question: as with everything in our Tech Stack, if a _compelling_ case is made for a particular technology/tool/library, then we can use it. But as you will no doubt have noticed, there was no effort made to _discuss_ the use of **`MOOR`** prior to using it. For the foreseeable future, No.

**Comment by nelsonic** [comment]
https://pub.dev/packages/moor_flutter discontinued:
<img width="1145" alt="image" src="https://user-images.githubusercontent.com/194400/200676181-e5e0306b-e574-4e6c-b9bb-344c8476df72.png">

Renamed: "drift" https://drift.simonbinder.eu -> https://github.com/simolus3/drift

# `GOTO`: https://github.com/dwyl/learn-flutter/issues/70

Thanks again for opening this issue @th0mas ❤️
