### ISSUE TITLE
Which features are more important in an Todo List

### ISSUE THREAD

**Issue by miguelmartins17** [dwyl/flutter-todo-list-tutorial#6]
There are several Checklist/ Todo List which are the most important features to make the application functional for everyone?
What should we include in the Todo List?

**Comment by iteles** [comment]
@miguelmartins17 Good question!
As with https://github.com/dwyl/javascript-todo-list-tutorial, it would be good to follow the [ToDoMVC](https://github.com/dwyl/javascript-todo-list-tutorial#todomvc) application.

The key features are:
+ Add an item to the to-do list
+ Toggle the item status to 'done'
+ Update/edit an item in the to-do list

Those are the essentials and then there is this list of small but interesting pieces of functionality to carry out: https://github.com/dwyl/javascript-todo-list-tutorial#requirements

If you follow the Javascript version of this tutorial, it will lay out the basic features one by one as you go through, so it may well be worth going through and listing those here first - then seeing if you feel any are unimportant 😊

**Comment by nelsonic** [comment]
Migelão, 
As described in #2 8 days ago, the point is to build a _complete_ Todo List Application with _all_ the features of the TodoMVC Specification  https://github.com/tastejs/todomvc/blob/master/app-spec.md 
This is mentioned **3 _times_** in the https://github.com/dwyl/javascript-todo-list-tutorial 
![todomvc-spec](https://user-images.githubusercontent.com/194400/73479708-5e9e3680-4390-11ea-810a-f8c6ddf104f9.png)

If you _followed all_ the steps in the `javascript-todo-list-tutorial` as instructed,
you would have built a Todo List with _all_ the features of TodoMVC and you would have _all_ your answers. Then _all_ you need to is _copy_ the format and replicate it in Flutter by _borrowing_ the code in https://github.com/brianegan/flutter_architecture_samples 

<hr />

Please don't fall into the trap where you "_**don't know what to do** so you **do nothing**_", after communication the biggest _superpower_ you can develop is _proactivity_. 
It's the _number 1_ habit of highly effective people is _proactivity_. https://en.wikipedia.org/wiki/The_7_Habits_of_Highly_Effective_People

If you haven't read the book (_which I gave to Edu a few years ago_), _listen_ to the Audiobook!
[![image](https://user-images.githubusercontent.com/194400/73464587-11fa3180-4377-11ea-90ec-1eb77342cd01.png)](https://youtu.be/UY7dRxK5siQ)
https://youtu.be/UY7dRxK5siQ
Doing _nothing_ out of ["_ignorance_"](https://en.wikipedia.org/wiki/Argument_from_ignorance) of the requirements is _fine_ in school, but it will get you fired pretty quickly in the real world. 

> "_I didn't know what work to do so I just sat here chilling on my phone messaging my friends_" ... 

Does that _sound_ like someone who is going to be _successful_ in life?

Learn _fast_ and write code _every_ day like **your _life_ depends on it**.

If you have any further questions for what needs to be done, please leave _comments_ on #2
