### ISSUE TITLE
TodoMVC for Flutter 

### ISSUE THREAD

**Issue by miguelmartins17** [dwyl/flutter-todo-list-tutorial#7]
Can I use TodoMVC also in the Flutter tutorial? Since it includes Dart can I also use the example in the Javascript Tutorial in the Flutter tutorial?

**Comment by miguelmartins17** [comment]
The **_Dart_** language is also mentioned within TodoMVC.


![Screen Shot 2020-01-30 at 17 53 17](https://user-images.githubusercontent.com/27420533/73476083-84740d00-4389-11ea-8167-7825a607c58a.png)

**Comment by iteles** [comment]
@miguelmartins17 I wouldn't get distracted by this before you have ticked off all the items in #2 that @nelsonic put together for you!

**Comment by nelsonic** [comment]
Miguel, please stop opening new issues for each question and then ignoring the answer when someone takes the time out of their day to craft a reply. 
You _haven't_ followed _all_ the steps in the issue I opened opened **8 days ago**. Just follow the instructions. 

I included a link to the code samples for "inspiration":
![flutter-todo-list-how-section](https://user-images.githubusercontent.com/194400/73476159-a66d8f80-4389-11ea-89ef-b62dd469a009.png)
https://github.com/brianegan/flutter_architecture_samples
![todomvc-for-flutter](https://user-images.githubusercontent.com/194400/73476339-f51b2980-4389-11ea-8b00-a5b7a5741e37.png)

The repository I linked to already has *all* the **TodoMVC** `code` for the tutorial!
Literally _all_ you have to do is go through the code that someone `else` has already written, _build_ the app and write out the steps. Which in turn is just a matter of _copying_ the steps in https://github.com/dwyl/javascript-todo-list-tutorial ... 

Literally someone else has done the "homework" for you and is _telling_ you _copy_! 
_All_ you have to do is show a _little_ effort/initiative. 

If you have any further questions please leave them as _comments_ in issue #2.
